# Generated by Django 3.2.9 on 2021-11-16 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211116_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 10, 53, 59, 766134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
