# Generated by Django 3.2.9 on 2021-11-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_events_eventdnt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
