# Generated by Django 3.2.9 on 2021-11-16 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventTitle', models.TextField(default='Nothing')),
                ('eventspeakers', models.TextField(default='N/A')),
                ('eventDescription', models.TextField(default='Nothing')),
                ('eventImage', models.ImageField(default='app/images/blog-post-2.jpg', upload_to='eventImg')),
                ('eventdnt', models.DateTimeField(default=datetime.datetime(2021, 11, 16, 10, 57, 14, 564726, tzinfo=utc))),
                ('eventDate', models.TextField(default='1-1-1970 - 1')),
                ('eventDuration', models.TextField(default='1pm - 2pm')),
                ('eventid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
