# Generated by Django 3.0.8 on 2021-11-17 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211117_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Nothing')),
                ('description', models.TextField(default='Nothing')),
                ('date', models.TextField(default='Nothing')),
                ('image', models.ImageField(upload_to='achievmentsImg')),
                ('datent', models.DateTimeField(default=datetime.datetime(2021, 11, 17, 17, 21, 14, 627528, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 17, 21, 14, 624822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='img',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
