# Generated by Django 3.2.9 on 2021-11-21 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211117_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=1)),
                ('pname', models.CharField(max_length=100)),
                ('ppic1', models.ImageField(default='blank', upload_to='pics')),
                ('ppic2', models.ImageField(default='blank', upload_to='pics')),
                ('ppic3', models.ImageField(default='blank', upload_to='pics')),
                ('ppic4', models.ImageField(default='blank', upload_to='pics')),
                ('ppic5', models.ImageField(default='blank', upload_to='pics')),
                ('ppic6', models.ImageField(default='blank', upload_to='pics')),
                ('ppic7', models.ImageField(default='blank', upload_to='pics')),
                ('ppic8', models.ImageField(default='blank', upload_to='pics')),
                ('ppic9', models.ImageField(default='blank', upload_to='pics')),
                ('ppic10', models.ImageField(default='blank', upload_to='pics')),
                ('pdesc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 5, 50, 31, 166772, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 5, 50, 31, 164791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
