# Generated by Django 3.2.9 on 2021-11-21 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211121_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='images',
            field=models.FileField(default='blank', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 12, 35, 45, 204394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 12, 35, 45, 203393, tzinfo=utc)),
        ),
    ]
