# Generated by Django 3.2.9 on 2021-11-21 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211121_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallary',
            old_name='pdesc',
            new_name='egname',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='images',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='pname',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='ppic1',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='ppic10',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='ppic2',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='ppic3',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='ppic4',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='ppic5',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='ppic6',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='ppic7',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='ppic8',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='ppic9',
        ),
        migrations.AddField(
            model_name='gallary',
            name='egimage',
            field=models.FileField(default='blank', upload_to=''),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 12, 50, 36, 524198, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 12, 50, 36, 522199, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='GallaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='pics')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.gallary')),
            ],
        ),
    ]
