# Generated by Django 3.2.9 on 2021-11-21 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211121_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 12, 58, 14, 886286, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 12, 58, 14, 885287, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='egimage',
            field=models.FileField(default='blank', upload_to='pics'),
        ),
    ]
