# Generated by Django 3.2.9 on 2021-11-21 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211121_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallary',
            new_name='Gallery',
        ),
        migrations.RenameModel(
            old_name='GallaryImage',
            new_name='GalleryImage',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 13, 14, 12, 183198, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 13, 14, 12, 181198, tzinfo=utc)),
        ),
    ]
