# Generated by Django 3.2.9 on 2021-11-30 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211129_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.PositiveIntegerField()),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 13, 30, 27, 83029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 13, 30, 27, 82030, tzinfo=utc)),
        ),
    ]
