# Generated by Django 3.2.5 on 2022-01-03 04:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211130_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 4, 15, 35, 108604, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 4, 15, 35, 106584, tzinfo=utc)),
        ),
    ]
