# Generated by Django 4.0 on 2022-01-04 04:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220103_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='date',
            new_name='Month',
        ),
        migrations.AddField(
            model_name='achievements',
            name='Year',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 4, 59, 24, 69633, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 4, 59, 24, 68637, tzinfo=utc)),
        ),
    ]
