# Generated by Django 4.0 on 2022-01-04 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_date_achievements_month_achievements_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='Month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='achievements',
            old_name='Year',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 5, 0, 15, 793405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 5, 0, 15, 792409, tzinfo=utc)),
        ),
    ]
