# Generated by Django 4.0 on 2022-01-04 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_month_achievements_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 5, 3, 25, 774777, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='month',
            field=models.CharField(default='Nothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 5, 3, 25, 773717, tzinfo=utc)),
        ),
    ]
