# Generated by Django 4.0 on 2022-01-04 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_achievements_datent_alter_achievements_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 9, 43, 19, 712207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 9, 43, 19, 711211, tzinfo=utc)),
        ),
    ]
