# Generated by Django 4.0 on 2022-01-07 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_achievements_datent_alter_events_eventdnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 6, 10, 4, 927420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 6, 10, 4, 925430, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='egimage',
            field=models.FileField(default='blank', upload_to='galleryImage'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='images',
            field=models.FileField(upload_to='galleryImage'),
        ),
    ]
