# Generated by Django 4.0 on 2022-01-07 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_achievements_datent_alter_events_eventdnt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='email',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 7, 11, 38, 406888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 7, 11, 38, 404895, tzinfo=utc)),
        ),
    ]
