# Generated by Django 4.0 on 2022-01-07 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_ourteam_email_alter_achievements_datent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='role',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 7, 14, 19, 77660, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 7, 14, 19, 75623, tzinfo=utc)),
        ),
    ]
