# Generated by Django 4.0 on 2022-01-07 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_ourteam_role_alter_achievements_datent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalmember', models.PositiveIntegerField(default=0)),
                ('localmember', models.PositiveIntegerField(default=0)),
                ('eventsno', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 11, 21, 39, 984730, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 11, 21, 39, 981821, tzinfo=utc)),
        ),
    ]
