# Generated by Django 4.0 on 2022-01-07 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_counting_alter_achievements_datent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting',
            name='yearsofexp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 11, 40, 21, 931757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 11, 40, 21, 930760, tzinfo=utc)),
        ),
    ]
