# Generated by Django 3.2.9 on 2022-01-08 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_counting_yearsofexp_alter_achievements_datent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemForm',
            new_name='LocalmemberForm',
        ),
        migrations.AlterField(
            model_name='achievements',
            name='datent',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 7, 38, 50, 398114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdnt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 7, 38, 50, 397113, tzinfo=utc)),
        ),
    ]
